ETrading_MVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ETrading_MVC.Models;


namespace ETrading_MVC.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin

        //To get All the BusinessOwners List
        public ActionResult GetBusinessOwnerDetails()
        {
            List<BusinessOwnerVM> businessOwnerList = new List<BusinessOwnerVM>();
            using (HttpClient client = new HttpClient())
            {
                var result = client.GetAsync("https://localhost:44377/api/AdminBusinessOwner").Result;
                if (result.IsSuccessStatusCode)
                {
                    businessOwnerList = result.Content.ReadAsAsync<List<BusinessOwnerVM>>().Result;
                    return View(businessOwnerList);
                }
            }
            return View();
        }

        // To get all the customers list
        public ActionResult GetCustomersDetails()
        {
            List<CustomerVM> custList = new List<CustomerVM>();
            using (HttpClient client = new HttpClient())
            {
                var result = client.GetAsync("https://localhost:44377/api/AdminCustomer").Result;
                if (result.IsSuccessStatusCode)
                {
                    custList = result.Content.ReadAsAsync<List<CustomerVM>>().Result;
                    return View(custList);
                }
            }
            return View();
        }

        // GET: Admin/Create
        // To create new BusinessOwner
        public ActionResult CreateBusinessOwner()
        {
            List<CategoryVM> catlist = new List<CategoryVM>();
            HttpClient client = new HttpClient();
            var result = client.GetAsync("https://localhost:44377/api/AdminCategory").Result;
            if (result.IsSuccessStatusCode)
            {
                catlist = result.Content.ReadAsAsync<List<CategoryVM>>().Result;
                SelectList sl = new SelectList(catlist, "CategoryId", "CategoryName");
                TempData["category"] = sl;
                TempData.Keep();
            }
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        public ActionResult CreateBusinessOwner(BusinessOwnerVM bo)
        {
            try
            {
                // TODO: Add insert logic here
                HttpClient client = new HttpClient();
                var result = client.PostAsJsonAsync("https://localhost:44377/api/BusinessOwner", bo).Result;

                if (result.IsSuccessStatusCode)
                {
                    var companyId = result.Content.ReadAsStringAsync().Result;
                    return RedirectToAction("GetBusinessOwnerDetails");
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // To create new customer
        public ActionResult createCustomers()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult createCustomers(CustomerVM cust)
        {
            try
            {
                HttpClient client = new HttpClient();
                var result = client.PostAsJsonAsync("https://localhost:44377/api/AdminCustomer", cust).Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetCustomersDetails");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }
        // GET: Admin/Delete/5
        public ActionResult DeleteCustomer(short id)
        {
            try
            {
                HttpClient client = new HttpClient();
                var result = client.DeleteAsync("https://localhost:44377/api/AdminCustomer/" + id.ToString()).Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetCustomersDetails");
                }
                else
                {
                    TempData["Message"] = "Customer can't be deleted";
                    TempData.Keep();
                    return RedirectToAction("GetCustomersDetails");
                }
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View("GetCustomersDetails");
            }
            return View("GetCustomersDetails");
        }

        //Admin Login
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(AdminLoginVM ad)
        {
            HttpClient client = new HttpClient();
            var result = client.GetAsync("https://localhost:44377/api/Admin?email=" + ad.email + "&password=" + ad.password).Result;
            if (result.IsSuccessStatusCode)
            {
                var res = result.Content.ReadAsAsync<Object>().Result;
                if (res.ToString() == "1")
                {
                    Session["username"] = ad.email;
                    return RedirectToAction("GetCustomersDetails");
                }
                else
                {
                    ViewBag.Message = "Invalid Username/Password";
                    Session["auth"] = "Authorization Failed";
                    return View();
                }

            }
            return View();

        }

        // To logout
        public ActionResult Logout()
        {
            if (Session["username"] != null)
            {
                Session["username"] = null;
                return RedirectToAction("Login");
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

    }
}

ETrading_MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ETrading_MVC.Models;

namespace ETrading_MVC.Controllers
{
    public class CustomerController : Controller
    {
        //GET : Login
        //Customer - MVC -Login - httpget
        public ActionResult LoginCustomer()
        {
            return View();
        }

        //LOGIN-Customer -MVC -HTTPPOST
        [HttpPost]
        public ActionResult LoginCustomer(LoginVM lg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (HttpClient client = new HttpClient())
                    {
                        var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + lg.email + "&password=" + lg.password).Result;
                        if (result.IsSuccessStatusCode)
                        {
                            var res = result.Content.ReadAsAsync<Object>().Result;

                            if (res.ToString().Equals("1"))
                            {
                                Session["UserEmail"] = lg.email;

                                return RedirectToAction("details", new { email = Session["UserEmail"] });
                            }
                            else if (res.ToString().Equals("0"))
                            {
                                ViewBag.msg = "Invalid Username/Password";
                            }
                            return View();
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // GET: Customer/Details/5
        //Customer -MVC-View Profile
        public ActionResult Details(string email)
        {
            try
            {
                CustomerVM custList = new CustomerVM();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        custList = result.Content.ReadAsAsync<CustomerVM>().Result;
                        return View(custList);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }

            return View();
        }

        //GET Account Balance
        // Customer - MVC -Display balance
        public ActionResult GetBalance(string mail)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?mail=" + mail).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var balance = result.Content.ReadAsAsync<Object>().Result;
                        ViewBag.res = "Account Balance :  " + balance;
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // GET: Customer/Create
        // Customer - MVC - Register
        public ActionResult CreateCustomer()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult CreateCustomer(CustomerVM cust)
        {
            try
            {
                // TODO: Add insert logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.PostAsJsonAsync("https://localhost:44377/api/Customer", cust).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var custid = result.Content.ReadAsAsync<Object>().Result;
                        ModelState.Clear();
                        ViewData["custid"] = "CUSTOMER ID: " + custid;
                        return RedirectToAction("LoginCustomer");
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: Customer/Edit/5
        // Customer - Mvc -Edit profile
        public ActionResult Edit(string email)
        {
            try
            {
                CustomerVM custList = new CustomerVM();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        custList = result.Content.ReadAsAsync<CustomerVM>().Result;
                        return View(custList);
                    }
                }
                return View("Details");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // POST: Customer/Edit/5
        // Customer - MVC - Edit Profile
        [HttpPost]
        public ActionResult Edit(string email, CustomerVM cust)
        {
            try
            {
                // TODO: Add update logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.PutAsJsonAsync("https://localhost:44377/api/Customer?email=" + email, cust).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return View("details", cust);
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        //Customer - MVC -Logout
        public ActionResult Logout()
        {
            if (Session["username"] != null)
            {
                Session["username"] = null;
                return RedirectToAction("LoginCustomer");
            }
            else
            {
                return RedirectToAction("LoginCustomer");
            }
        }
    }
}

ETrading_MVC/Views/Admin/CreateBusinessOwner.cshtml
@model ETrading_MVC.Models.BusinessOwnerVM

@{
    ViewBag.Title = "CreateBusinessOwner";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h2>CreateBusinessOwner</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BusinessOwnerVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OwnerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OwnerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OwnerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyPasscode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyPasscode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyPasscode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfIncorporation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfIncorporation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfIncorporation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, TempData["category"] as SelectList, "-- Select Category--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SharePrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SharePrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SharePrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NoOfShares, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoOfShares, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoOfShares, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ETrading_MVC/Views/Admin/GetBusinessOwnerDetails.cshtml
@model IEnumerable<ETrading_MVC.Models.BusinessOwnerVM>

@{
    ViewBag.Title = "GetBusinessOwnerDetails";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h2>Business Owners List</h2>

<p>
    @Html.ActionLink("Create New", "CreateBusinessOwner")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CompanyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfIncorporation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CompanyAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SharePrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NoOfShares)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OwnerEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfIncorporation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CompanyAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SharePrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NoOfShares)
        </td>
       
    </tr>
}

</table>

ETrading_MVC/Views/Admin/GetCustomersDetails.cshtml
@model IEnumerable<ETrading_MVC.Models.CustomerVM>

@{
    ViewBag.Title = "GetCustomersDetails";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h2><b>Customers Details</b></h2>


<p>
    @Html.ActionLink("Create New", "createCustomers")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        
        <th>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountBalance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.CustomerEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountBalance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.ActionLink("Delete", "DeleteCustomer", new { id=item.CustomerId })
        </td>
    </tr>
}


</table>
<h4>@TempData["Message"]</h4>

ETrading_MVC/Views/Admin/Login.cshtml
@model ETrading_MVC.Models.AdminLoginVM

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Admin/_AdminLogin.cshtml";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AdminLogin</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
    @ViewBag.Message
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ETrading_MVC/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })@*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*<li>@Html.ActionLink("LogOut", "Logout", "Customer")</li>*@

                    @if (Session["username"] != null)
                    {
                        <li>@Html.ActionLink("Company Details", "GetBusinessOwnerDetails", "Admin", null)</li>
                        <li>@Html.ActionLink("Customer Details", "GetCustomersDetails", "Admin", null)</li>

                        <li>@Html.ActionLink("Create New BusinessOwner", "CreateBusinessOwner", "Admin", null)</li>
                        <li>@Html.ActionLink("Create New Customer", "createCustomers", "Admin", null)</li>


                        <li><a href="#">Hi @Session["username"]</a></li>
                        <li>@Html.ActionLink("Logout", "Logout", "Admin")</li>
                    }
                </ul>

                @*@@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Trading Application</p>
        </footer>
    </div>

    @*  @Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ETrading_MVC/Views/Admin/_AdminLogin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log in", "Login", "BusinessOnwer", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Trading Application</p>
        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ETrading_MVC/Views/Admin/createCustomers.cshtml
@model ETrading_MVC.Models.CustomerVM

@{
    ViewBag.Title = "createCustomers";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<h2>createCustomers</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CustomerVM</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}