ETrading_MVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ETrading_MVC.Models;

namespace ETrading_MVC.Controllers
{
    public class CustomerController : Controller
    {
        //GET : Login
        //Customer - MVC -Login - httpget
        public ActionResult LoginCustomer()
        {
            return View();
        }

        //LOGIN-Customer -MVC -HTTPPOST
        [HttpPost]
        public ActionResult LoginCustomer(LoginVM lg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (HttpClient client = new HttpClient())
                    {
                        var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + lg.email + "&password=" + lg.password).Result;
                        if (result.IsSuccessStatusCode)
                        {
                            var res = result.Content.ReadAsAsync<Object>().Result;

                            if (res.ToString().Equals("1"))
                            {
                                Session["UserEmail"] = lg.email;

                                return RedirectToAction("details", new { email = Session["UserEmail"] });
                            }
                            else if (res.ToString().Equals("0"))
                            {
                                ViewBag.msg = "Invalid Username/Password";
                            }
                            return View();
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // GET: Customer/Details/5
        //Customer -MVC-View Profile
        public ActionResult Details(string email)
        {
            try
            {
                CustomerVM custList = new CustomerVM();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        custList = result.Content.ReadAsAsync<CustomerVM>().Result;
                        return View(custList);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }

            return View();
        }

        //GET Account Balance
        // Customer - MVC -Display balance
        public ActionResult GetBalance(string mail)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?mail=" + mail).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var balance = result.Content.ReadAsAsync<Object>().Result;
                        ViewBag.res = "Account Balance :  " + balance;
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // GET: Customer/Create
        // Customer - MVC - Register
        public ActionResult CreateCustomer()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult CreateCustomer(CustomerVM cust)
        {
            try
            {
                // TODO: Add insert logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.PostAsJsonAsync("https://localhost:44377/api/Customer", cust).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var custid = result.Content.ReadAsAsync<Object>().Result;
                        ModelState.Clear();
                        ViewData["custid"] = "CUSTOMER ID: " + custid;
                        return RedirectToAction("LoginCustomer");
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: Customer/Edit/5
        // Customer - Mvc -Edit profile
        public ActionResult Edit(string email)
        {
            try
            {
                CustomerVM custList = new CustomerVM();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Customer?email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        custList = result.Content.ReadAsAsync<CustomerVM>().Result;
                        return View(custList);
                    }
                }
                return View("Details");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // POST: Customer/Edit/5
        // Customer - MVC - Edit Profile
        [HttpPost]
        public ActionResult Edit(string email, CustomerVM cust)
        {
            try
            {
                // TODO: Add update logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.PutAsJsonAsync("https://localhost:44377/api/Customer?email=" + email, cust).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        return View("details", cust);
                    }
                }
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        //Customer - MVC -Logout
        public ActionResult Logout()
        {
            if (Session["username"] != null)
            {
                Session["username"] = null;
                return RedirectToAction("LoginCustomer");
            }
            else
            {
                return RedirectToAction("LoginCustomer");
            }
        }
    }
}

ETrading_MVC/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ETrading_MVC.Models;

namespace ETrading_MVC.Controllers
{
    public class TransactionController : Controller
    {
        // GET: Transaction
        //CustomerTransaction- MVC -Display Shareprice
        public ActionResult Index()
        {
            try
            {
                List<SharePriceVM> spList = new List<SharePriceVM>();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Transaction").Result;
                    if (result.IsSuccessStatusCode)
                    {
                        spList = result.Content.ReadAsAsync<List<SharePriceVM>>().Result;
                        return View(spList);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        // GET: Transaction/Details/5
        //CustomerTransaction - MVC -Display Transaction
        public ActionResult DetailTransaction(string email)
        {
            try
            {
                List<TransactionVM> tranList = new List<TransactionVM>();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Transaction?email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        tranList = result.Content.ReadAsAsync<List<TransactionVM>>().Result;
                        return View(tranList);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }
        //Get company list
        //CustomerTransaction - MVC - Display All Company
        public ActionResult GetCompanyList()
        {
            try
            {
                List<BusinessOwnerVM> complist = new List<BusinessOwnerVM>();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/AdminBusinessOwner").Result;
                    if (result.IsSuccessStatusCode)
                    {
                        complist = result.Content.ReadAsAsync<List<BusinessOwnerVM>>().Result;

                        return View(complist);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }
        //GET Company details
        //CustomerTransaction - MVC -Display CompanyDetails
        public ActionResult DisplayCompanyDetails(short id)
        {
            try
            {
                BusinessOwnerVM com = new BusinessOwnerVM();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/Transaction/" + id.ToString()).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        com = result.Content.ReadAsAsync<BusinessOwnerVM>().Result;
                        return View(com);
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        //BuyShares 
        //CustomerTransaction - MVC - Buyshares
        [HttpGet]
        public ActionResult BuyShares(string email)
        {
            try
            {
                List<BuySharesVM> buyshareList = new List<BuySharesVM>();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/AdminBusinessOwner").Result;
                    if (result.IsSuccessStatusCode)
                    {
                        buyshareList = result.Content.ReadAsAsync<List<BuySharesVM>>().Result;
                        SelectList sl = new SelectList(buyshareList, "CompanyId", "CompanyName");

                        TempData["company"] = sl;
                        TempData.Keep();
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        //BuyShares
        //CustomerTransaction -MVC-Buyshares
        [HttpPost]
        public ActionResult BuyShares(string email, BuySharesVM bs)
        {
            try
            {
                TempData.Keep();
                // TODO: Add update logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/transaction?companyId=" + bs.companyId.ToString() + "&shareQuantity=" + bs.shareQuantity.ToString() + "&email=" + email).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var status = result.Content.ReadAsAsync<Object>().Result;
                        ModelState.Clear();

                        //ViewBag.msg = status;                        
                        if (status.ToString().Equals("0"))
                        {
                            ViewBag.msg = "Unable to Buy ,Not enough share";
                        }
                        else if (status.ToString().Equals("1"))
                        {
                            ViewBag.msg = "Unable to Buy,insufficient balance";
                        }
                        else if (status.ToString().Equals("2"))
                        {
                            ViewBag.msg = "Share bought successfully";
                        }
                        else if (status.ToString().Equals("3"))
                        {
                            ViewBag.msg = "No such company";
                        }
                        return View();
                    }
                }
                return RedirectToAction("detailtransaction", new { email = email });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        //CustomerTransaction - MVC -Sellshares
        [HttpGet]
        public ActionResult SellShares(string email)
        {
            try
            {
                List<SellSharesVM> buyshareList = new List<SellSharesVM>();
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/AdminBusinessOwner").Result;
                    if (result.IsSuccessStatusCode)
                    {
                        buyshareList = result.Content.ReadAsAsync<List<SellSharesVM>>().Result;
                        SelectList sl = new SelectList(buyshareList, "companyid", "CompanyName");
                        TempData["company"] = sl;
                        TempData.Keep();
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
            return View();
        }

        //SellShares
        //CustomerTransaction - MVC -Sellshares
        [HttpPost]
        public ActionResult SellShares(string email, SellSharesVM ss)
        {
            try
            {
                TempData.Keep();
                // TODO: Add update logic here
                using (HttpClient client = new HttpClient())
                {
                    var result = client.GetAsync("https://localhost:44377/api/transaction?email=" + email + "&numberofShares=" + ss.numberofShares + "&companyid=" + ss.companyid).Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var status = result.Content.ReadAsAsync<short>().Result;
                        ModelState.Clear();

                        //ViewBag.res = status;
                        if (status.ToString().Equals("0"))
                        {
                            ViewBag.msg = "Shares Sold Successfully";
                        }
                        else if (status.ToString().Equals("1"))
                        {
                            ViewBag.msg = "Unable to sell,Not enough shares";
                        }
                        else if (status.ToString().Equals("2"))
                        {
                            ViewBag.msg = "Unable to sell,No shares of this company ";
                        }
                        else if (status.ToString().Equals("3"))
                        {
                            ViewBag.msg = "No such company";
                        }
                        return View();
                    }
                }
                return RedirectToAction("detailtransaction", new { email = email });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

    }
}

ETrading_MVC/Views/Customer/CreateCustomer.cshtml
@model ETrading_MVC.Models.CustomerVM

@{
    ViewBag.Title = "CreateCustomer";
    Layout = "~/Views/Customer/_RegisterLoginLayout.cshtml";
}

<h2>Register Customer</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
    @ViewData["custid"]
}

<div>
    @Html.ActionLink("Back to Home", "Index", "Home")
</div>

ETrading_MVC/Views/Customer/Details.cshtml
@model ETrading_MVC.Models.CustomerVM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Customer/_CustomerLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccountBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountBalance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>

ETrading_MVC/Views/Customer/Edit.cshtml
@model ETrading_MVC.Models.CustomerVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Customer/_CustomerLayout.cshtml";
}

<h2>Edit Profile</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    @ViewBag.msg
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

ETrading_MVC/Views/Customer/GetBalance.cshtml
@{
    ViewBag.Title = "GetBalance";
    Layout = "~/Views/Customer/_CustomerLayout.cshtml";
}

<h2>GetBalance</h2>
<h3>@ViewBag.res</h3>

ETrading_MVC/Views/Customer/_CustomerLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("View Profile", "Details", "Customer", new { email = Session["UserEmail"] }, null)</li>
                    <li>@Html.ActionLink("Edit Profile", "Edit", "Customer", new { email = Session["UserEmail"] }, null)</li>
                    <li>@Html.ActionLink("Account Balance", "GetBalance", "Customer", new { mail = Session["UserEmail"] }, null)</li>
                    <li>@Html.ActionLink("Display Transactions", "detailtransaction", "Transaction", new { email = Session["UserEmail"] }, null)</li>
                    @*<li>@Html.ActionLink("View All", "Index", "Customer")</li>*@
                    <li>@Html.ActionLink("Display Company List", "GetCompanyList", "Transaction")</li>
                    <li>@Html.ActionLink("Display SharePrice", "Index", "Transaction")</li>
                    <li>@Html.ActionLink("Buy Shares", "BuyShares", "Transaction", new { email = Session["UserEmail"] }, null)</li>
                    <li>@Html.ActionLink("Sell Shares", "SellShares", "Transaction", new { email = Session["UserEmail"] }, null)</li>

                    @if (Session["UserEmail"] != null)
                    {
                        <li><a href="#">Hi @Session["UserEmail"]</a></li>
                        <li>@Html.ActionLink("LogOut", "Logout", "Customer")</li>
                    }
                </ul>

                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <br />
    <br />
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Trading Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ETrading_MVC/Views/Customer/_RegisterLoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Register", "CreateCustomer", "Customer", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("Log in", "LoginCustomer", "Customer", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - E-Trading Application</p>
        </footer>
    </div>
    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>